### ISSUE TITLE
Very annoyed

### ISSUE THREAD

**Issue by SaphiLC** [spatie/laravel-db-snapshots#65]
Any reason the snapshot i created didn't save my users table!?

Used `php artisan snapshot:create`, no errors, everything else is saved but the users table... and the server we have have no backups... so... why the users table is not saved??

Edit. Actually it didnt save 3 tables... the last 3 in alphabetical order... i really don't understand why this happened since i got no errors...

**Comment by freekmurze** [comment]
There's too little very me to go on here. The testsuite proves that the code is working as intended. If you have a specific error please PR a failing test for me to take a look at.

**Comment by SaphiLC** [comment]
As i said, it gave no errors at all, we lost all our users and the stats of every business in our websites, thanks. I'll rethink using any of your packages in the future, tired of using something that has no support at all, i know you are busy, you dont charge any money and blah blah, but all you ever do when someone asks for support is ask for PRs & Tests and close the threads (and looks like you don't even read the issues either because i said "no errors" and you are asking for a specific error test PR).

**Comment by AndrewFeeney** [comment]
@SaphiLC I believe what @freekmurze is asking for is for you to write a test which fails, that would pass if the package was behaving as you expected, and submit a PR containing that test. That way it's clear to everyone what the expected behaviour is, and if changes are needed, there is a test ready to go which will pass when the changes have the desired effect. Without that, it's really very difficult if not impossible for a package maintainer to replicate the unexpected behaviour you are experiencing, which is the first step in determining whether or not a fix is required and what that fix is. Does that make sense?

**Comment by SaphiLC** [comment]
> @SaphiLC I believe what @freekmurze is asking for is for you to write a test which fails, that would pass if the package was behaving as you expected, and submit a PR containing that test. That way it's clear to everyone what the expected behaviour is, and if changes are needed, there is a test ready to go which will pass when the changes have the desired effect. Without that, it's really very difficult if not impossible for a package maintainer to replicate the unexpected behaviour you are experiencing, which is the first step in determining whether or not a fix is required and what that fix is. Does that make sense?

```
Used php artisan snapshot:create, no errors, everything else is saved but the users table and 2 other tables
```
thats all i did, followed the instructions at https://github.com/spatie/laravel-db-snapshots step by step, i dont know how to make the tests he always asks for, not everyone uses those or required to use those.
But whatever, hope no one else gets this problem, already fixed/patched the mess this package caused to us, thanks tho

**Comment by AndrewFeeney** [comment]
@SaphiLC I understand your frustration. These situations can certainly be frustrating. 

That said, it's probably worth having a glance at the contributing guidelines. https://github.com/spatie/laravel-db-snapshots/blob/master/CONTRIBUTING.md

Remember that this code is free, and comes with no warranty. Maintainers frequently receive abusive communication from disgruntled users, and it's not very motivating to spend time for free diagnosing a user's problem when they have not provided enough information to reproduce the error, and are apparently hostile from the outset. Consider how you would feel if a package you maintained for free received a comment like the first one you posted. You've since stated that you weren't annoyed at the maintainers themselves, which is good, but at least in my opinion it wasn't at all clear that you were frustrated at the situation and not at the maintainers themselves.

This could be a good opportunity to dip your toes in the water in automated testing, which would no doubt help you write better code. The test case you probably want to look at is this one:

https://github.com/spatie/laravel-db-snapshots/blob/master/tests/Commands/CreateTest.php

Best of luck! Glad you sorted the issue out on your end.
